version: '3.8'

services:
  web:
    build: .
    volumes:
      - ..:/workspace:cached
    ports:
      - 5173:5173
    command: /bin/sh -c "while sleep 1000; do :; done"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
