version: '3.8'

services:
  web:
    container_name: web
    hostname: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - 5173:5173
    command: npm run dev

  db:
    container_name: db
    hostname: db
    image: postgres:17.5
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: local
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
